### ISSUE TITLE
 Issue with Integrating Phomemo D30 Printer in Flutter App

### ISSUE THREAD

**Issue by Rabee-Omran** [Knightro63/phomemo#3]
Hi,

I'm reaching out about an issue we're encountering while integrating the Phomemo D30 label printer with our Flutter app. We've followed various methods using packages like phomemo and flutter_blu_plus to establish communication with the printer, but we're currently stuck at a point where we can connect successfully but are unable to print anything meaningful. Instead, we're receiving unexpected byte notifications (e.g., [1, 1]).

We've ensured all necessary permissions for Bluetooth and location services are granted within our Android app.

To summarize, our main concerns are:

1. We need advice on the recommended way for printing to the Phomemo D30 printer.
2. Any sample code snippets or examples demonstrating printer connection, sending print data, and handling necessary configurations would be invaluable.

Thank you for your attention to this matter.

Best regards,

![photo_2024-05-02_13-54-28](https://github.com/Knightro63/phomemo/assets/66083931/d7698ffa-af59-45c4-b823-45697dfa7134)

```


  img.Image? letter = await helper.generateImage(
      const TextSpan(
        text: "test",
        style: TextStyle(fontSize: 24, color: Colors.black),
      ),
      size: size * 8,
    );

    await label.printLabel(
      [letter],
      printer: printer,
      labelSize: const Size(10, 10),
      spacing: 0,
      rotate: false,
    ).then((value) {
      printing = false;
      emit(LabelPrinterPrintingDone(allowPrinting: state.allowPrinting));
    });
  }

```

my blu file:

```

import 'dart:async';
import 'dart:math';
import 'package:flutter/foundation.dart';
import 'package:flutter_blue_plus/flutter_blue_plus.dart';

enum BluetoothOptions {
  SEARCHING,
  CONNECTING,
  CONNECTED,
  RECEIVED_SERVICES,
  DISCONNECTED,
  DATA_RECEIVED,
  STOP_SEARCHING
}

typedef BluetoothCallback = void Function(BluetoothOptions options);

class Bluetooth {
  Bluetooth({
    required this.onUpdate,
    required this.names,
    required this.deviceChange,
  }) {
    _startScan();
    FlutterBluePlus.adapterState.listen((state) {
      _updateAdapterState(state);
      _startScan();
    });
  }
  final List<String> names;
  late BluetoothCallback onUpdate;
  final Function(BluetoothDevice? device) deviceChange;
  BluetoothDevice? selectedDevice;
  List<BluetoothCharacteristic>? characteristics;
  BluetoothAdapterState adapterState = BluetoothAdapterState.on;
  bool scanning = false;
  bool get isScanning => scanning;

  void _updateAdapterState(BluetoothAdapterState state) {
    adapterState = state;
    if (adapterState == BluetoothAdapterState.on) {
      _startScan();
    }
  }

  void _startScan() async {
    if (!isScanning && adapterState == BluetoothAdapterState.on) {
      onUpdate(BluetoothOptions.SEARCHING);
      scanning = true;
      await FlutterBluePlus.startScan(timeout: const Duration(seconds: 15));

      StreamSubscription<List<ScanResult>>? scanSubscription;

      scanSubscription = FlutterBluePlus.scanResults.listen(
        (results) {
          if (results.isNotEmpty) {
            _processScanResult(results);
          }
        },
        onError: (e, stackTrace) {},
        onDone: () {
          // scanSubscription?.cancel();
          // scanning = false;
          // onUpdate(BluetoothOptions.STOP_SEARCHING);
        },
      );

      Future.delayed(const Duration(minutes: 2), () {
        if (scanning) {
          _stopScan("Timeout");
        }
      });
    }
  }

  void _stopScan(String reason) {
    scanning = false;
    // onUpdate(BluetoothOptions.STOP_SEARCHING);
    FlutterBluePlus.stopScan();
  }

  void _processScanResult(List<ScanResult> scanResult) {
    for (var result in scanResult) {
      if (names.isNotEmpty &&
          result.device.platformName.trim().isNotEmpty &&
          names.contains(result.device.platformName)) {
        _connect(result.device);
        _stopScan("Connecting");
        break;
      }
    }
  }

  void _connect(BluetoothDevice device) {
    onUpdate(BluetoothOptions.CONNECTING);
    selectedDevice = device;
    deviceChange(selectedDevice);

    if (kDebugMode) {
      print(selectedDevice!.platformName);
    }
    device.connect(mtu: null).then((_) {
      onUpdate(BluetoothOptions.CONNECTED);
      _discoverServices();
    });
  }

  void _handleNotificationData(List<int> data) {
    print('Received data =======> ${data.toString()}');
  }

  void _discoverServices() async {
    if (selectedDevice != null) {
      List<BluetoothService> services =
          await selectedDevice!.discoverServices();
      if (services.isNotEmpty) {
        for (var service in services) {
          characteristics = service.characteristics;
          for (var characteristic in service.characteristics) {
            if (characteristic.properties.notify) {
              characteristic.setNotifyValue(true);
              characteristic.lastValueStream.listen(_handleNotificationData,
                  onError: (error) {
                print('Received data =======> ${error.toString()}');
              });
              break;
            }
          }
        }
        onUpdate(BluetoothOptions.RECEIVED_SERVICES);
      }
    }
  }

  void _readCharacteristic() async {
    BluetoothCharacteristic? toSend;
    for (var char in characteristics!) {
      if (char.properties.notify) {
        toSend = char;
      }
    }
    List<int> value = await toSend!.read();
  }

  void readBluetoothData() {
    _readCharacteristic();
  }

  Future<List<int>> read() async {
    BluetoothCharacteristic? toSend;
    for (var char in characteristics!) {
      if (char.properties.notify) {
        toSend = char;
      }
    }
    return await toSend!.read();
  }

  Future<void> write(List<int> data) async {
    BluetoothCharacteristic? toSend;
    for (var char in characteristics!) {
      if (char.properties.write) {
        toSend = char;
      }
    }

    await toSend!.write("HHH".codeUnits,
        withoutResponse: true, allowLongWrite: false, timeout: 200000);
  }

  void destroy() {
    FlutterBluePlus.stopScan();
  }
}

```

**Comment by Knightro63** [comment]
Hi @Rabee-Omran,

I have updated the example to use flutter_blue_plus. Flutter_blue_plus only allows up to 197 bits to be sent, so it is a little slower.  The example also has bluetooth permission handler to ask for permissions from the device if not granted already. I only have a D35 right now, so I was unable to check with a D30. Both the D30 and the D35 use the same protocol, so it should work.

Make sure to follow the requirements for bluetooth permission on what ever device you are using. I have tested it using macOS, iOS, and android.

Hope this helps.

**Comment by Rabee-Omran** [comment]
Hi @Knightro63,

Thank you for your detailed response. I've implemented the suggestions you provided, but unfortunately, I'm still facing issues with the Phomemo D30 printer. The unexpected byte notifications persist.

To provide more context, I'm including relevant snippets of my Android manifest, Bluetooth handling file, and the relevant parts of my Flutter Cubit for your review:

**AndroidManifest.xml** (Permissions):
```xml
    <uses-permission android:name="android.permission.INTERNET"/>
     <!-- Allow Bluetooth -->
     <uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />

     <!-- New Bluetooth permissions in Android 12
     https://developer.android.com/about/versions/12/features/bluetooth-permissions -->
     <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
     <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
 
     <!-- legacy for Android 11 or lower -->
     <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
     <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="30"/>
 
 
     <!-- legacy for Android 9 or lower -->
     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="28" />

```

**Bluetooth File** (Bluetooth handling):
```dart

import 'dart:async';
import 'package:flutter_blue_plus/flutter_blue_plus.dart';

enum BluetoothOptions {
  searching,
  connecting,
  connected,
  receivedServices,
  disconnected,
  dataReceived,
  stopSearching
}

typedef BluetoothCallback = void Function(BluetoothOptions options);

class Bluetooth {
  Bluetooth({BluetoothCallback? onUpdate, List<Guid>? services, this.names}) {
    guid = services ?? [];
    if (onUpdate != null) {
      _callbacks.add(onUpdate);
    }
    FlutterBluePlus.adapterState.listen((onData) {
      state = onData;
    });
  }

  List<String>? names;
  List<Guid> guid = [];

  final List<BluetoothCallback> _callbacks = [];
  BluetoothConnectionState deviceState = BluetoothConnectionState.disconnected;
  BluetoothAdapterState state = BluetoothAdapterState.unknown;

  FlutterBluePlus flutterBlue = FlutterBluePlus();

  BluetoothDevice? device;
  List<BluetoothCharacteristic>? characteristic;
  List<ScanResult>? scanResults;
  List<BluetoothService> services = [];

  bool hasDevices = false;
  bool hasServices = false;
  bool get isScanning => subscription != null;
  Timer? timer;

  StreamSubscription<List<ScanResult>>? subscription;

  bool deviceConnected() {
    return (deviceState == BluetoothConnectionState.connected);
  }

  void addCallback(BluetoothCallback callback) {
    _callbacks.add(callback);
  }

  void _onUpdate(BluetoothOptions option) {
    for (int i = 0; i < _callbacks.length; i++) {
      _callbacks[i].call(option);
    }
  }

  void startScan() {
    print("Starting Scan on App Bar");
    if (state == BluetoothAdapterState.on) {
      _btScan();
    }
  }

  void _btScan() async {
    if (subscription == null) {
      print("Scanning");
      bool allowScan = true;
      bool didStop = false;
      _onUpdate(BluetoothOptions.searching);
      subscription = FlutterBluePlus.scanResults.listen((scanResult) {
        if (allowScan && scanResult.isNotEmpty) {
          if (names != null) {
            for (int i = 0; i < names!.length; i++) {
              if (scanResult[0].device.platformName.toLowerCase() ==
                  names![i].toLowerCase()) {
                scanResults = scanResult;
                stopScan("Connecting Name");
                print(scanResult[0].device);
                print("=============");
                _connect(scanResult[0].device);
                allowScan = false;
                didStop = true;
                break;
              }
            }
          } else {
            print(scanResult[0].device.platformName);
            allowScan = false;
          }
        }
      }, onDone: () {
        if (!didStop) {
          stopScan("Done");
        }
        subscription?.cancel();
        subscription = null;
        _onUpdate(BluetoothOptions.stopSearching);
      }, onError: (e) {
        print(e);
      });
      const Duration d = Duration(minutes: 2);
      FlutterBluePlus.cancelWhenScanComplete(subscription!);
      FlutterBluePlus.startScan(
          timeout: d,
          androidUsesFineLocation: true,
          withNames: names ?? [],
          withServices: guid);

      timer = Timer(d, stopScan);
    }
  }

  void stopScan([String type = '']) {
    timer?.cancel();
    timer = null;
    print('STOPSCAN:$type');
    subscription?.cancel();
    subscription = null;
    _onUpdate(BluetoothOptions.stopSearching);
    FlutterBluePlus.stopScan();
  }

  void _connect(BluetoothDevice d) async {
    _onUpdate(BluetoothOptions.connecting);
    device = d;
    device!.connectionState.listen((onData) {
      if (onData == BluetoothConnectionState.disconnected &&
          deviceConnected()) {
        print("Disconnecting From Device!");
        device?.disconnect();
        print("Device Disconnected!");
        _onUpdate(BluetoothOptions.disconnected);
        hasServices = false;
        device = null;
      }
      deviceState = onData;
    });

    device!.connect().then((error) {
      _onUpdate(BluetoothOptions.connected);
      _getServices();
    });
  }

  void _getServices() async {
    services = await device!.discoverServices();
    for (var service in services) {
      characteristic = service.characteristics;
    }
    //_readCharacteristic();
    print(characteristic);
    print("===================================");
    _onUpdate(BluetoothOptions.receivedServices);
    hasServices = true;
  }

  void disconnect() {
    device?.disconnect().then((value) {
      deviceState = BluetoothConnectionState.disconnected;
      print("Device Disconnected!");
      _onUpdate(BluetoothOptions.disconnected);
      hasServices = false;
      device = null;
    });
  }

  void dispose() {
    stopScan();
    disconnect();
  }

  void getBleData() {
    _readCharacteristic();
  }

  void _readCharacteristic() async {
    List<int> value = await read();
  }

  Future<List<int>> read() async {
    BluetoothCharacteristic? toSend;
    for (var char in characteristic!) {
      if (char.properties.notify) {
        toSend = char;
      }
    }
    return await toSend!.read();
  }

  Future<void> write(List<int> data) async {
    BluetoothCharacteristic? toSend;
    for (var char in characteristic!) {
      if (char.properties.write) {
        toSend = char;
      }
    }
    await toSend?.write(data);
  }
}

```

**Flutter Cubit** (Printer integration):
```dart
// ignore_for_file: depend_on_referenced_packages
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_blue_plus/flutter_blue_plus.dart';
import 'package:image/image.dart' as img;
import 'package:permission_handler/permission_handler.dart';
import 'package:phomemo/phomemo.dart';
import 'package:pos_kitchen_display/features/sale/domain/entities/sale_bill.dart';
import 'package:pos_kitchen_display/features/sale/domain/entities/sale_bill_item.dart';
import '../bluetooth.dart';
part 'label_printer_state.dart';

class LabelPrinterCubit extends Cubit<LabelPrinterState> {
  LabelPrinterCubit() : super(LabelPrinterInitial(allowPrinting: false));

  late Bluetooth bluetooth;
  BluetoothOptions? bleOptions;
  bool printing = false;
  BluetoothDevice? selectedDevice;
  void init() {
    bluetooth = Bluetooth(
      onUpdate: _bleUpdate,
      names: ['P12Pro', 'D35', 'D30'],
    );
  }

  void _bleUpdate(BluetoothOptions options) {
    switch (options) {
      case BluetoothOptions.disconnected:
        emit(LabelPrinterDisconnected(allowPrinting: state.allowPrinting));
        break;
      case BluetoothOptions.connected:
        emit(LabelPrinterConnected(allowPrinting: state.allowPrinting));
        break;
      case BluetoothOptions.dataReceived:
        emit(LabelPrinterDataReceived(allowPrinting: state.allowPrinting));
        break;
      default:
        emit(LabelPrinterDefault(allowPrinting: state.allowPrinting));
        break;
    }
  }

  Future<void> toggleAllowPrinting(bool allowPrinting) async {
    emit(LabelPrinterDefault(allowPrinting: allowPrinting));
  }

  Future<void> printText(SaleBill bill, SaleBillItem item) async {
    if (state.allowPrinting) {
      if (bluetooth.deviceConnected()) {
        await printPhomemo(bill: bill, item: item);
      } else if (!bluetooth.isScanning && bluetooth.device == null) {
        if (((Platform.isMacOS || Platform.isIOS) &&
                await Permission.bluetooth.request().isGranted) ||
            (Platform.isAndroid &&
                await Permission.bluetoothScan.request().isGranted &&
                await Permission.bluetoothConnect.request().isGranted)) {
          bluetooth.startScan();
        }
      } else if (bluetooth.isScanning && bluetooth.device == null) {
        bluetooth.stopScan();
      }
    }
  }

  Future<void> printPhomemo({
    required SaleBill bill,
    required SaleBillItem item,
    Size? size,
  }) async {
    size ??= const Size(double.infinity, 12);
    if (printing) return;
    printing = true;
    Phomemo label =
        Phomemo(send: bluetooth.write, read: bluetooth.read, packetSize: 128);
    PhomemoHelper helper = PhomemoHelper();
    PhomemoPrinter printer =
        helper.getPrinterFromName(bluetooth.device!.platformName);

    if (printer == PhomemoPrinter.d35 && size.width == double.infinity) {
      size = Size(25, size.height);
    }
    String name = "";
    if (bill.customer?.fullName.isNotEmpty ?? false) {
      name = bill.customer!.fullName;
    } else if (bill.name.trim().isNotEmpty) {
      name = bill.name.trim();
    } else if (item.notes.trim().isNotEmpty) {
      name = item.notes.trim();
    }

    img.Image? letter = name.isNotEmpty
        ? await helper.generateImage(
            TextSpan(
              text: name,
              style: const TextStyle(
                  fontFamily: 'MuseoSans', fontSize: 34, color: Colors.black),
            ),
            size: size * 8,
          )
        : null;

    await label.printLabel(
      [letter],
      printer: printer,
      spacing: 5,
    ).then((value) {
      printing = false;
      emit(LabelPrinterPrintingDone(allowPrinting: state.allowPrinting));
    });
  }
}

```

the printer characteristic:

![t](https://github.com/Knightro63/phomemo/assets/66083931/ca56b79f-c9aa-424e-b47d-1709e5e29ef8)


Additionally, I want to clarify that the Phomemo D30 printer is printing fine and correctly from its own companion app.

Given the setup, I'd like to ask for further guidance:

1. Should I configure anything specific on the Phomemo D30 printer itself or within its companion app?
2. Are there additional configurations or steps that need to be performed in the Flutter code beyond what's standard for Bluetooth communication?
3. Is there a specific data format or protocol that the Phomemo D30 requires for successful printing?

Any insights or additional steps you can suggest would be greatly appreciated. Thank you for your ongoing assistance with this issue.

Best regards,

**Comment by Knightro63** [comment]
Hi @Rabee-Omran,

I am sorry to hear to you are still having an issue. 

You do not need to do anything to the printer to connect and send info to it. The api packs the information into the corrected format and sends it to the printer in packs by the size you set. Flutter Blue Plus only allows packs up to 197 bits, so change the packetSize to 128. 

In the image you sent it looks like the printer is connecting, but I am unable to tell if it is sending the info to the printer. For the D30 might need a different footer packet than the one I wrote. 

Can you try with macOS or iOS to see if there is just an android specific issue. I tested with a samsung SM T500, google pixel 7, mac m1, and an iPhone X.

I will try to see if any other packages use a different protocol to get it to work.

Sorry for the inconvenience and please let me know if another os works.

**Comment by Rabee-Omran** [comment]
Hi @Knightro63,

Thank you for your continued support and guidance.

I've adjusted the packetSize to 128 and tested the app on different platforms, including a real iPhone device, but unfortunately, I'm still encountering the same issue with unexpected byte notifications.

At this point, I'm considering if the Phomemo D30 requires a different footer packet format than the one I've implemented. How can I determine the correct footer packet format for the D30 printer? Any guidance on identifying and implementing the correct footer packet would be immensely helpful.

Additionally, would it be possible to discuss this further via email or perhaps arrange a Google Meet session? My email address is rabeeomran2@gmail.com. I believe a more direct conversation could expedite the troubleshooting process.

Thank you once again for your patience and assistance. I look forward to hearing from you soon.

Best regards,

Rabee

**Comment by Knightro63** [comment]
Hi @Rabee-Omran,

I have ordered a D30 to test and make sure I can get it to work. 

I have a D35 P12Pro and M220 here that I have tested to make sure they were working. The D30 was the first one I tested many months ago so I could have messed something up and that is why this is no longer working. 

After looking into it the footer that is there seems to be right. The Header could be the thing that needs to be changed. It might not need some of the beginning info. 

If you want to test this change in the phomemo file 

```dart
    List<int> start = [
      0x1b,
      0x40,
      0x1d,
      0x76,
      0x30,
      0x00,
      width % 256,
      width ~/ 256,
      bytes % 256,
      bytes ~/ 256
    ];
```

to 

```dart
    List<int> start = [
      0x1f // might be D30 only
      0x11 // might be D30 only
      0x24 // might be D30 only
      0x00 // might be D30 only
      0x1b
      0x40
      0x1d
      0x76
      0x30
      0x00
      0x0c //size
      0x00 //size
      0x40 //bytes
      0x01 //bytes
    ];
```

Here is a reference I used to get phomemo printers to work [here](https://github.com/polskafan/phomemo_d30/blob/master/print_text.py) and [here](https://github.com/vivier/phomemo-tools).

Please let me know if this works. Also will update if it does. When I get the printer in I will test as well.

Hope this helps.

**Comment by Rabee-Omran** [comment]
Hi @Knightro63,

Thank you very much for your detailed guidance and the suggested changes to the `phomemo` file. I really appreciate your effort in ordering the Phomemo D30 printer to assist with this troubleshooting.

I will implement the header configuration changes you provided tomorrow. I'll test the updated setup thoroughly and will definitely let you know the outcome.

Once again, thank you for your ongoing support and assistance. I'm looking forward to working together to resolve this issue with the Phomemo D30 printer integration.

I'll be in touch with my findings after testing.

Best regards,

**Comment by Rabee-Omran** [comment]
Hi @Knightro63,

I wanted to update you that I've tested the new header configuration you suggested for the Phomemo D30 printer integration, but unfortunately, it did not resolve the issue. The printing still does not work as expected.

I'm currently awaiting your test results with the D30 printer that you ordered. Please let me know how it goes once you've had a chance to test it on the D30.

In the meantime, if there are any other suggestions or configurations you recommend from my side, please let me know. I'm eager to work together to troubleshoot and resolve this issue.

Thank you once again for your continued support and assistance.

Best regards,

Rabee

**Comment by Rabee-Omran** [comment]
Hi @Knightro63,

I hope this message finds you well. I wanted to check in and see if you have received the Phomemo D30 printer you ordered for testing purposes. If so, have you had the chance to try it out and verify the configurations?

Any updates or insights you can provide based on your direct testing with the D30 printer would be greatly appreciated. If you have encountered any specific issues or stumbled upon potential solutions, please share them with me.

I'm still actively working on resolving the printer integration problem from my end, but your hands-on experience with the actual D30 hardware could prove invaluable in narrowing down the root cause and finding a reliable solution.

Please let me know if you need any additional information or assistance from my side. I'm eager to collaborate and make progress on this matter.

Thank you for your continued support and patience throughout this process. I look forward to hearing from you soon.

Best regards,
Rabee

**Comment by Knightro63** [comment]
Hi @Rabee-Omran,

I just received the phomemo D30 and I was able to connect with my mac run the example code typed in "Test" and it ran no problem. Worked just as expected. 

1. Are you trying to print an image that is not printing correctly?
2. Is it printing at all?

The only time it did not work is when there was no tape in the printer, if the info I sent was way to long for the printer to process e.g.(This is a very long message that wont be able to be printed.) with out changing the width of the size `size ??= const Size(40,12);`, or if the tape got stuck.

I am assuming that the height has not been adjusted. 

Tap Sizes:
p12pro: `size ??= const Size(double.infinity,12);`
D35: `double width = 40; size ??= Size(width,12);` width can be different depending on the tape placed in.
D30: `size ??= const Size(40,12);`
m220: `double width = 40; double height = 120; size ??= Size(width,height);` width and height can be different depending on the tape placed in.

Hope this helps.

**Comment by Rabee-Omran** [comment]
Hi @Knightro63,

Thank you for updating me on your successful connection and testing with the Phomemo D30 printer on your Mac. It's great to hear that the example code ran smoothly without any issues.

Unfortunately, I'm still experiencing difficulties with the printing process on my end. Despite successfully connecting to the printer (which I can confirm through console logs), I'm unable to print anything meaningful.

To provide more clarity and facilitate troubleshooting, I will send you the relevant sections of my code where I suspect the issue might be occurring. This will help identify any potential bugs or misconfigurations that could be affecting the printing functionality.

I will attach both my Cubit file and Bluetooth handling file for your review.

Once again, thank you for your assistance and support throughout this process. I'm hopeful that together we can pinpoint the issue and get the Phomemo D30 printer integrated successfully with my Flutter app.

**Bluetooth File** (Bluetooth handling):
```dart
// ignore_for_file: avoid_print, unused_local_variable

import 'dart:async';
import 'package:flutter_blue_plus/flutter_blue_plus.dart';

enum BluetoothOptions {
  searching,
  connecting,
  connected,
  receivedServices,
  disconnected,
  dataReceived,
  stopSearching
}

typedef BluetoothCallback = void Function(BluetoothOptions options);

class Bluetooth {
  Bluetooth({BluetoothCallback? onUpdate, List<Guid>? services, this.names}) {
    guid = services ?? [];
    if (onUpdate != null) {
      _callbacks.add(onUpdate);
    }
    FlutterBluePlus.adapterState.listen((onData) {
      state = onData;
    });
  }

  List<String>? names;
  List<Guid> guid = [];

  final List<BluetoothCallback> _callbacks = [];
  BluetoothConnectionState deviceState = BluetoothConnectionState.disconnected;
  BluetoothAdapterState state = BluetoothAdapterState.unknown;

  FlutterBluePlus flutterBlue = FlutterBluePlus();

  BluetoothDevice? device;
  List<BluetoothCharacteristic>? characteristic;
  List<ScanResult>? scanResults;
  List<BluetoothService> services = [];

  bool hasDevices = false;
  bool hasServices = false;
  bool get isScanning => subscription != null;
  Timer? timer;

  StreamSubscription<List<ScanResult>>? subscription;

  bool deviceConnected() {
    return (deviceState == BluetoothConnectionState.connected);
  }

  void addCallback(BluetoothCallback callback) {
    _callbacks.add(callback);
  }

  void _onUpdate(BluetoothOptions option) {
    for (int i = 0; i < _callbacks.length; i++) {
      _callbacks[i].call(option);
    }
  }

  void startScan() {
    print("Starting Scan on App Bar");
    if (state == BluetoothAdapterState.on) {
      _btScan();
    }
  }

  void _btScan() async {
    if (subscription == null) {
      print("Scanning");
      bool allowScan = true;
      bool didStop = false;
      _onUpdate(BluetoothOptions.searching);
      subscription = FlutterBluePlus.scanResults.listen((scanResult) {
        if (allowScan && scanResult.isNotEmpty) {
          if (names != null) {
            for (int i = 0; i < names!.length; i++) {
              if (scanResult[0].device.platformName.toLowerCase() ==
                  names![i].toLowerCase()) {
                scanResults = scanResult;
                stopScan("Connecting Name");
                print(scanResult[0].device);
                print("=============");
                _connect(scanResult[0].device);
                allowScan = false;
                didStop = true;
                break;
              }
            }
          } else {
            print(scanResult[0].device.platformName);
            allowScan = false;
          }
        }
      }, onDone: () {
        if (!didStop) {
          stopScan("Done");
        }
        subscription?.cancel();
        subscription = null;
        _onUpdate(BluetoothOptions.stopSearching);
      }, onError: (e) {
        print(e);
      });
      const Duration d = Duration(minutes: 2);
      FlutterBluePlus.cancelWhenScanComplete(subscription!);
      FlutterBluePlus.startScan(
          timeout: d,
          androidUsesFineLocation: true,
          withNames: names ?? [],
          withServices: guid);

      timer = Timer(d, stopScan);
    }
  }

  void stopScan([String type = '']) {
    timer?.cancel();
    timer = null;
    print('STOPSCAN:$type');
    subscription?.cancel();
    subscription = null;
    _onUpdate(BluetoothOptions.stopSearching);
    FlutterBluePlus.stopScan();
  }

  void _connect(BluetoothDevice d) async {
    _onUpdate(BluetoothOptions.connecting);
    device = d;
    device!.connectionState.listen((onData) {
      if (onData == BluetoothConnectionState.disconnected &&
          deviceConnected()) {
        print("Disconnecting From Device!");
        device?.disconnect();
        print("Device Disconnected!");
        _onUpdate(BluetoothOptions.disconnected);
        hasServices = false;
        device = null;
      }
      deviceState = onData;
    });

    device!.connect().then((error) {
      _onUpdate(BluetoothOptions.connected);
      _getServices();
    });
  }

  void _getServices() async {
    services = await device!.discoverServices();
    for (var service in services) {
      characteristic = service.characteristics;
    }
    //_readCharacteristic();
    print(characteristic);
    print("===================================");
    _onUpdate(BluetoothOptions.receivedServices);
    hasServices = true;
  }

  void disconnect() {
    device?.disconnect().then((value) {
      deviceState = BluetoothConnectionState.disconnected;
      print("Device Disconnected!");
      _onUpdate(BluetoothOptions.disconnected);
      hasServices = false;
      device = null;
    });
  }

  void dispose() {
    stopScan();
    disconnect();
  }

  void getBleData() {
    _readCharacteristic();
  }

  void _readCharacteristic() async {
    List<int> value = await read();
  }

  Future<List<int>> read() async {
    BluetoothCharacteristic? toSend;
    for (var char in characteristic!) {
      if (char.properties.notify) {
        toSend = char;
      }
    }
    return await toSend!.read();
  }

  Future<void> write(List<int> data) async {
    BluetoothCharacteristic? toSend;
    for (var char in characteristic!) {
      if (char.properties.write) {
        toSend = char;
      }
    }
    await toSend?.write(data);
  }
}

```




**Cubit File** (print handling):
```dart
// ignore_for_file: depend_on_referenced_packages
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_blue_plus/flutter_blue_plus.dart';
import 'package:image/image.dart' as img;
import 'package:permission_handler/permission_handler.dart';
import 'package:phomemo/phomemo.dart';
import 'package:pos_kitchen_display/features/sale/domain/entities/sale_bill.dart';
import 'package:pos_kitchen_display/features/sale/domain/entities/sale_bill_item.dart';
import '../bluetooth.dart';
part 'label_printer_state.dart';

class LabelPrinterCubit extends Cubit<LabelPrinterState> {
  LabelPrinterCubit() : super(LabelPrinterInitial(allowPrinting: false));

  late Bluetooth bluetooth;
  BluetoothOptions? bleOptions;
  bool printing = false;
  BluetoothDevice? selectedDevice;
  void init() {
    bluetooth = Bluetooth(
      onUpdate: _bleUpdate,
      names: ['P12Pro', 'D35', 'D30'],
    );
  }

  void _bleUpdate(BluetoothOptions options) {
    switch (options) {
      case BluetoothOptions.disconnected:
        emit(LabelPrinterDisconnected(allowPrinting: state.allowPrinting));
        break;
      case BluetoothOptions.connected:
        emit(LabelPrinterConnected(allowPrinting: state.allowPrinting));
        break;
      case BluetoothOptions.dataReceived:
        emit(LabelPrinterDataReceived(allowPrinting: state.allowPrinting));
        break;
      default:
        emit(LabelPrinterDefault(allowPrinting: state.allowPrinting));
        break;
    }
  }

  Future<void> toggleAllowPrinting(bool allowPrinting) async {
    emit(LabelPrinterDefault(allowPrinting: allowPrinting));
  }

  Future<void> printText(SaleBill bill, SaleBillItem item) async {
    if (state.allowPrinting) {
      if (bluetooth.deviceConnected()) {
        await printPhomemo(bill: bill, item: item);
      } else if (!bluetooth.isScanning && bluetooth.device == null) {
        if (((Platform.isMacOS || Platform.isIOS) &&
                await Permission.bluetooth.request().isGranted) ||
            (Platform.isAndroid &&
                await Permission.bluetoothScan.request().isGranted &&
                await Permission.bluetoothConnect.request().isGranted)) {
          bluetooth.startScan();
        }
      } else if (bluetooth.isScanning && bluetooth.device == null) {
        bluetooth.stopScan();
      }
    }
  }

  Future<void> printPhomemo({
    required SaleBill bill,
    required SaleBillItem item,
    Size? size,
  }) async {
    size ??= const Size(double.infinity, 12);
    if (printing) return;
    printing = true;
    Phomemo label =
        Phomemo(send: bluetooth.write, read: bluetooth.read, packetSize: 128);
    PhomemoHelper helper = PhomemoHelper();
    PhomemoPrinter printer =
        helper.getPrinterFromName(bluetooth.device!.platformName);

    if (printer == PhomemoPrinter.d35 && size.width == double.infinity) {
      size = Size(25, size.height);
    }
    String name = "";
    if (bill.customer?.fullName.isNotEmpty ?? false) {
      name = bill.customer!.fullName;
    } else if (bill.name.trim().isNotEmpty) {
      name = bill.name.trim();
    } else if (item.notes.trim().isNotEmpty) {
      name = item.notes.trim();
    }

    img.Image? letter = name.isNotEmpty
        ? await helper.generateImage(
            TextSpan(
              text: name,
              style: const TextStyle(
                  fontFamily: 'MuseoSans', fontSize: 34, color: Colors.black),
            ),
            size: size * 8,
          )
        : null;

    await label.printLabel(
      [letter],
      printer: printer,
      spacing: 5,
    ).then((value) {
      printing = false;
      emit(LabelPrinterPrintingDone(allowPrinting: state.allowPrinting));
    });
  }
}

```

i just want to print the text (customer name) and i'm on Android platfrom

Looking forward to your feedback once you've had a chance to review the code.

Best regards,

Rabee

**Comment by Knightro63** [comment]
Hi @Rabee-Omran,

`size ??= const Size(double.infinity, 12);` is for a p12pro. 
The D30 does not allow for infinite sizing. Please change to `size ??= const Size(40, 12);` or `await printPhomemo(bill: bill, item: item, size: Size(40, 12));`.  The size of the text will auto change height if the the width is too long with `helper.generateImage`. 

The D30 at full height will only allow for about 13 characters depending on the character. 

Hope this helps

**Comment by Knightro63** [comment]
Hi @Rabee-Omran,

I have updated the example to give a better picture of how to use the printer. I also added the ability to make a widget into a Image. This will also display what the label will look like before printing. I will publish the new version soon.

Hope this helps.

**Comment by Rabee-Omran** [comment]
Hi @Knightro63,

I wanted to provide an update that unfortunately, I'm still experiencing the same issue with the Phomemo D30 printer. While the printer successfully connects, it doesn't print anything despite changing the size settings.

To facilitate troubleshooting and ensure consistency in testing, would it be possible for you to create a comprehensive example package that includes all necessary files, including Android-specific configurations?

Having a complete example package would allow me to build an APK directly from the example and test it on my Android device. This approach could help isolate any platform-specific issues and provide a clearer path towards resolving the printing problem.

Your assistance in providing a full example package would be immensely valuable in diagnosing and addressing the integration issues with the Phomemo D30 printer.

Thank you for your continued support and collaboration on this matter.

Best regards,

Rabee

**Comment by Knightro63** [comment]
Hi @Rabee-Omran,

I am so confused. This should be working, if you can connect you should be able to send data. I used the xml manifest you provided to check. I will not be able to upload an android folder till Tuesday, but I don't think it is needed since you can connect to the printer already. 

1. Have you used the most recent example I provided?
2. When sending info does you terminal show an event when sending? (If not then you are not sending data. flutter_blue_plus spams you with messages every time you send a packet of data to the printer.)
3. In your code I am wondering if `String name = "";` ever gets a different value. Can you try just sending it any data. e.g.(`String name = "Test";`) As I commented in 2 you should receive about 3-4 lines of info in your terminal for every packet sent. 
5. Is it possible to get access to you full code on github to see if I can get it working?

Sorry this is not working. I hope we can solve the issue you are having soon.

**Comment by Rabee-Omran** [comment]
Hi @Knightro63,

No problem, I can wait until Tuesday for you to upload the Android folder.

For point 3, yes, I have tried sending a fixed string instead of using the variable name. I still encounter the same issue.

For point 4, I will attach a link to the repository so that you can take a look at the full code and test it on your Android device. Please let me know if you need any edits or modifications to the code.

https://github.com/Rabee-Omran/test-phomemo

that example in repo above not work for me and it not print anything.

I have also tried your most recent example that you provided, and I have tested this on a physical device as well.

I'm ready for a Google Meet or Zoom call if you're available, as it might be easier to discuss and troubleshoot the issue in real-time.

Please let me know if you need any further information or clarification and thank you for your continued support and collaboration on this matter.

Best regards,

Rabee

**Comment by Knightro63** [comment]
Hi @Rabee-Omran,

I found the issue you were having. There were some updates to some of the flutter dependencies files the were not in my pubspec.lock file. 

After running `flutter pub upgrade` I was getting the same issue you were.

I was able to resolve the issue after some time and have updated the `pub.dev` version.

Please add this to your yaml file.

```yaml
  phomemo:  ^0.0.2
  image: ^4.1.7
```

Hope this helps and resolves all the issues you were having.

**Comment by Rabee-Omran** [comment]
Hi @Knightro63,

I wanted to let you know that I tried updating the dependencies as you suggested, and it worked perfectly! The Phomemo D30 printer is now printing as expected.

Thank you so much for your dedication and for resolving this issue. Your support has been invaluable, and I really appreciate all the effort you've put into helping me with this integration.

Thanks again for everything!

Best regards,

Rabee
